### ISSUE TITLE
Handling of pyimzML written files

### ISSUE THREAD

**Issue by cKNUSPeR** [m2aia/pym2aia#8]
Hi, for some reason i get an unexpected error when reading imzML files that where written by pyimzML.
Here is the traceback:

On most datsets, i get the following error,  
  File "C:\Users\Jannik\Documents\Uni\Master_Biochem\4_Semester\QCdev\src\i2nca\i2nca\test.py", line 13, in <module>
    J = m2.ImzMLReader(file_dir)
  File "C:\Users\Jannik\.conda\envs\QCdev\lib\site-packages\m2aia\ImageIO.py", line 222, in __init__
    self.Load()
  File "C:\Users\Jannik\.conda\envs\QCdev\lib\site-packages\m2aia\ImageIO.py", line 234, in Load
    self.handle = self.lib.CreateImageHandle(cPath)
OSError: [WinError -529697949] Windows Error 0xe06d7363

but on one dataset, i'm able to get a more informative message:

Traceback (most recent call last):
  File "C:\Users\Jannik\Documents\Uni\Master_Biochem\4_Semester\QCdev\src\i2nca\i2nca\test.py", line 11, in <module>
    J= m2.ImzMLReader(out_path)
  File "C:\Users\Jannik\.conda\envs\QCdev\lib\site-packages\m2aia\ImageIO.py", line 222, in __init__
    self.Load()
  File "C:\Users\Jannik\.conda\envs\QCdev\lib\site-packages\m2aia\ImageIO.py", line 233, in Load
    cPath = create_string_buffer(self.imzML_path.encode())
AttributeError: 'NoneType' object has no attribute 'encode'

Since it goes down into the C++-parts, i am a bit lost. If i try to read old files written with pyimzML and pym2aia 0.3, everything is fine, but with newer files, i just get this error over and over again. 

Any help is much appreciated :D

**Comment by jtfcordes** [comment]
Hi, thank you for your message! 

Is it possible to load the files in the GUI [M2aia](https://github.com/m2aia/m2aia/releases/tag/v2024.01)?

**Comment by cKNUSPeR** [comment]
When run in the docker, the file can also not be read. however, the whole container crashes, so i was only able to obtain the output from the docker log, not the m2aia console that opened in the docker.

2024-01-30 11:06:27,923 INFO exited: m2aia (exit status 0; expected)
2024-01-30 11:06:27,926 WARN received SIGTERM indicating exit request
2024-01-30 11:06:27,935 INFO waiting for nginx, web, xvfb, wm, lxpanel, pcmanfm, x11vnc, novnc to die
2024-01-30 11:06:27,937 INFO stopped: lxpanel (terminated by SIGTERM)
2024-01-30 11:06:27,958 INFO stopped: xvfb (terminated by SIGKILL)
2024-01-30 11:06:27,978 INFO stopped: x11vnc (exit status 2)
2024-01-30 11:06:27,983 INFO stopped: novnc (exit status 143)
2024-01-30 11:06:28,032 INFO stopped: wm (exit status 1)
2024-01-30 11:06:28,139 ERROR Exception on /api/health [GET] (app.py:1890)
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2446, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1951, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1820, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1949, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1935, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/web/backend/vnc/app.py", line 41, in apihealth
if state.health:
File "/usr/local/lib/web/backend/vnc/state.py", line 129, in health
self._update_health()
File "/usr/local/lib/web/backend/vnc/state.py", line 31, in _update_health
output = gsp.check_output([
File "/usr/local/lib/python3.8/dist-packages/gevent/subprocess.py", line 348, in check_output
raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['supervisorctl', '-c', '/etc/supervisor/supervisord.conf', 'status']' returned non-zero exit status 1.
2024-01-30 11:06:31,190 WARN killing 'pcmanfm' (178) with SIGKILL
2024-01-30 11:06:31,190 INFO waiting for nginx, web, pcmanfm to die
2024-01-30 11:06:31,200 INFO stopped: pcmanfm (terminated by SIGKILL)
2024-01-30 11:06:32,204 INFO stopped: web (terminated by SIGTERM)
2024-01-30 11:06:32,267 INFO stopped: nginx (exit status 0)

I don't kniw how helpful that is.
Is there a way to stop the container from closing, so that i can get the log output?

**Comment by cKNUSPeR** [comment]
Also, i checked back with older versions. 
Files parsed with pym2aia 0.3.2 and written with pyimzML 1.5.3 can be parsed by m2aia 0.5.1 and 0.5.10,
but those initially parsed with 0.5.1 and then written by pyimzML 1.5.3 cannot be reopened in m2aia 0.5.1

**Comment by cKNUSPeR** [comment]
So, i've also tried the normal desktop app and i think the error mesage was was more informative:

Exception occured when reading file D:/wittej/data/docker_mount/c_error/output_conv_output_cont_profile.imzML:
C:\mitk\Modules\Core\src\DataManagement\mitkImage.cpp:763: 
ITK ERROR Image(0000024C5B8B07E8): Invalid dimension[0]:0


I'm gonna check if the imzML writer performs better when provided with a z dimension of 1

**Comment by cKNUSPeR** [comment]
So, i found the problem. 

for some reason, if the first pixel is written at (1,1,1), m2aia 0.5.1 can easily parse it.
But if the pixel is written at (0,0,0), the error occurs.

I can easily fix this on my side, but it migth be nice to have a more robust way of dealing with this.

Also, that leads me to another question: Is m2aia intended to be 0-based or 1-based when indexing? 
As the first spectrum gets assiged the id 0, (for reference .GetSpectrum(0) should give a valid spectrum of the first pixel),
but the coordinate indices seem to be 1-based. 
Empty pixels (when using a non quadratical dataset) also get assigned the Index 0 (at least, within the .GetIndexArray() method).

**Comment by jtfcordes** [comment]
Hi, I am happy that you have found the problem and thank you for the report.

Please take a look into the [imzML documentation](https://ms-imaging.org/wp-content/uploads/2009/08/specifications_imzML1.1.0_RC1.pdf) chapter "2.4 Orientation of images [...] The position 1/1 is in the top left corner."

I have already found a way to support imzML images starting with both (1/1) and (0/0) :) It will be part of the next release.

**M2aia is 0-based**, even for the index image!

```python
# Access valid spectrum IDs:: 
        
indexImage = I.GetIndexArray()
maskImage = I.GetMaskArray()
validIndices = indexImage[maskImage > 0]
```

I've updated the pyM2aia documentation for [GetIndexArray](https://data.jtfc.de/pym2aia/sphinx-build/html/m2aia.html#m2aia.ImageIO.ImzMLReader.GetIndexArray).

Thanks again!
